[package]
name = "rs-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.5"
dotenvy = "0.15.7"
redis = { version = "0.32.6", features = ["tokio-comp"] }
sea-orm = { git="https://github.com/SeaQL/sea-orm.git",branch="master"}
